# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    name: Build and Test on CI
    docker:
    # specify the version you desire here
    - image: circleci/node:8

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: npm test

  # build production
  deploy:
    name: Deploy to Production
    docker:
    - image: alpine/git:1.0.4
    working_directory: ~/repo

    steps:
    - checkout

#    - run:
#        name: Create build for production
#        command: git remote add heroku https://git.heroku.com/orders-platform.git

    - add_ssh_keys:
        fingerprints:
        - "27:11:9e:a4:61:38:7f:d5:3b:30:ee:b5:67:82:5f:96"
    - deploy:
        name: Deploy Master to Heroku (production)
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git push heroku https://git.heroku.com/orders-platform.git
          fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master