# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-front-end:
    name: Build and Test Front-End
    docker:
    # specify the version you desire here
    - image: circleci/node:8

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: Install Dependencies
        command: npm install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Run unit tests
        command: npm run test:unit

  test-back-end:
    name: Build and Test Back-End

    docker:
    - image: circleci/golang:1.10.4

    working_directory: ~/repo/backend/src/orders-management

    steps:
    - checkout

    - run:
        name: Install Dependencies
        command: go get github.com/mrjones/oauth

    - run:
        name: Build server
        command: env GOOS=linux GOARCH=amd64 go build -o main backend/src/orders-management/*.go

  build-and-deploy-to-dockerhub:
    name: Build and deploy to dockerhub
    machine: true
    steps:
    - checkout

    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - run: docker build -t jakeoblivion/orders-management:latest .

    - run: docker push jakeoblivion/orders-management:latest

  run-latest-over-ssh:
    name: Run latest docker image

    machine: true

    steps:
    - run: |
        ssh $SSH_USER@$SSH_HOST
        docker pull jakeoblivion/orders-management:latest
        docker run -p 80:3001 -t jakeoblivion/orders-management:latest

workflows:
  version: 2
  test-build-deploy-run:
    jobs:
    - test-front-end
    - test-back-end
    - build-and-deploy-to-dockerhub:
        requires:
        - test-front-end
        - test-back-end
        filters:
          branches:
            only: master
    - run-latest-over-ssh:
        requires:
        - build-and-deploy-to-dockerhub